[build]
  publish = "public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "v0.92.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://rsjeni.github.io/blog/"

